### ISSUE TITLE
Implement `vanguard` gRPC endpoint to provide past epochs for `orchestrator`

### ISSUE THREAD

**Issue by mxmar** [frozeman/vanguard-consensus-engine#14]
We need to prepare gRPC flow for providing past epochs data - past consensus info. It should be implemented like `func (bs *Server) StreamBlocks(req *ethpb.StreamBlocksRequest, stream ethpb.BeaconChain_StreamBlocksServer) error` is. 

We should consider about two cases:
a) beacon chain starts;
b) beacon chain is ongoing;

Past consensus info should come from helpers like `ProposerAssignments`.

**Comment by mxmar** [comment]
I should take a look on `StreamDuties(req *ethpb.DutiesRequest, stream ethpb.BeaconNodeValidator_StreamDutiesServer)` too. (`beacon-chain/rpc/validator/assignments.go`).

**Comment by atif-konasl** [comment]
@mxmar 

If there is not proposer to propose block in last slot(for example: 95) of the current epoch(for example: 2) then who and how to calculate proposer list for next epoch(3)?

We need to figure it out because, in the above case, `handleEpochBoundary(ctx context.Context, postState *stateTrie.BeaconState)` method does not call so no consensus info event is also triggered and `orchestrator` will also do not get the next epoch consensus info.

**Comment by mxmar** [comment]
@atif-konasl and what about `func (bs *Server) NextEpochProposerList(ctx context.Context, empty *ptypes.Empty) (*ethpb.ValidatorAssignments, error)` function?

**Comment by atif-konasl** [comment]
@mxmar `func (bs *Server) NextEpochProposerList(ctx context.Context, empty *ptypes.Empty) (*ethpb.ValidatorAssignments, error)` is our implemented api but we need to know how prysm actually handle in that case.

**Comment by mxmar** [comment]
Ok, got it @atif-konasl

**Comment by atif-konasl** [comment]
@mxmar I think you can follow this event api: `StreamDuties(req *ethpb.DutiesRequest, stream ethpb.BeaconNodeValidator_StreamDutiesServer)`. This api publishes duties after each epoch. So it does not need to wait for any event channel. 

We can also think similar fashion for api. Every last slot of current epoch, a ticker will tick then api will prepare the consensus info and publish the consensus info to orchestrator. If we follow this approach, then we do not need to trigger any event from `process_block.go` file as well as from other files.

**Comment by atif-konasl** [comment]
@mxmar 
please write implementation note(how do you implement this issue) in the issue description before start implementation. It would good for reviewers/developers to know about the implementation in the codebase.

**Comment by mxmar** [comment]
@atif-konasl 

Let's divide this:
a) next epoch - We're going with Blaise to prepare `nextEpochAssignments`  like
```
beacon-chain/core/helpers/committee.go:170
```
b) I need to know how to manage past epochs consensus info - should I focus on feed events flow like for e.g. `beacon-chain/core/feed/consensus/events.go` or work with validator `duties` approach? 
c) `Every last slot of current epoch, a ticker will tick then api will prepare the consensus info and publish the consensus info to orchestrator.` - You mean to check every tick for `currentSlot` if it's current epoch's last slot and then publish/notify orchestrator?
d) If `StreamConsensusInfo` then I should implement the same for `rpc/beacon` package. If yes maybe we should have `consensus_info.go` or something similar inside `beacon` package in `rpc`. What do you think? (In can when we use `StreamDuty` approach instead of feed events).

I would like to have unit/integration tests for this functionality (features).

**Comment by atif-konasl** [comment]
@mxmar 

`For b`: feed event does not work when last slot of any epoch is missing the block that means it also misses to publish the `consensusInfo`. So i would prefer `streamDuties` tick approach.
`For c`:  yes
`For d`:  yes and you need to have `consensus_info.go` file under `rpc/beacon` package like `StreamDuty`

Yes we must need unit tests and integration test should be for service.

**Comment by mxmar** [comment]
I will use https://github.com/lukso-network/vanguard-apis/tree/release/vanguard-apis branch as root for my features.

**Comment by atif-konasl** [comment]
okay

**Comment by mxmar** [comment]
> @mxmar
> 
> If there is not proposer to propose block in last slot(for example: 95) of the current epoch(for example: 2) then who and how to calculate proposer list for next epoch(3)?
> 
> We need to figure it out because, in the above case, `handleEpochBoundary(ctx context.Context, postState *stateTrie.BeaconState)` method does not call so no consensus info event is also triggered and `orchestrator` will also do not get the next epoch consensus info.

I want to have clear knowledge in this issue :) You were right, there were not working functionality for this, but right now it's implemented and working. PR was: https://github.com/lukso-network/vanguard-consensus-engine/pull/11

**Comment by mxmar** [comment]
Issue solved by https://github.com/lukso-network/vanguard-consensus-engine/pull/18
