### ISSUE TITLE
Header hash, extraData fields validation then sign executable block header hash using BLS key in validator client.

### ISSUE THREAD

**Issue by atif-konasl** [frozeman/vanguard-consensus-engine#2]
### Description
According to lukso mainnet architecture, validator client validates header `hash`, `extraData` fields. Then validator sign on header `hash`.

### Scope of this issue
- Add new validation method in `validator/client/propose.go` file.
- If the validator method returns true then validator will forward to the next steps otherwise validator will not propose new block.

> Need to add signature generation and verify method so that we can generate 32 bytes signature using bls key.
> According to @blazejkrzak, validator will sign using his bls private which is 96 bytes but we use only first 32 bytes of the bls signature for `mixDigest`

**Comment by blazejkrzak** [comment]
FYI:

- [ ] https://hackmd.io/gCBkJaLeRkiuHHmOnRLhOg?view
- [ ] https://github.com/lukso-network/pandora-execution-engine/pull/49
