### ISSUE TITLE
Implement a client for orchestrator for calling confirmation api.

### ISSUE THREAD

**Issue by atif-konasl** [frozeman/vanguard-consensus-engine#21]
### Overview
We need to implement orchestrator client just like `ethclient` package. This client will give you confirmation result of specific slots and block hashes.

### Responsibilities
- This client package will dial `orchestrator` client.
- This package expose a method which will call `orc_confirmBlockHashesVan` api with proper request object and response passed to its caller.

### Implementation Notes
_Please provide implementation notes_

**Comment by blazejkrzak** [comment]
its `orc_confirmVanBlockHashes`

**Comment by blazejkrzak** [comment]
https://gist.github.com/frozeman/d52090f3b8c4b654cacc279d894df31c

**Comment by mxmar** [comment]
PR link is: https://github.com/lukso-network/vanguard-consensus-engine/pull/24

**Comment by mxmar** [comment]
It's done and merged. Now in live tests phase (dev GCP network).

**Comment by mxmar** [comment]
Live test phase passed - by `dev` GCP.
