### ISSUE TITLE
Implement `minimalConsensusInfo` as a Vanguard subscription `van_subscribe`

### ISSUE THREAD

**Issue by mxmar** [frozeman/vanguard-consensus-engine#9]
### DESCRIPTION:

In connection with our documentation (https://gist.github.com/frozeman/d52090f3b8c4b654cacc279d894df31c#connection) we need to prepare subscription on the Vanguard side to have proper `minimalConsensusInfo` subscription. 

Currently orchestrator is calling `NextEpochProposerList` API to get consensus info. It will be changed when vanguard is ready to server consensus info using event subscription system. When vanguard event system for `van_subscribe: minimalConsensusInfo` will complete, we can test the whole flow. 

If we can achieve it, then we can test  the whole flow of consensus info propagation.

### FLOW: 
`van -> orc -> pan`

### GEIST DRAFT:
```
1. 🦺 orc > van: get validator list (committee) of epoch(s):
    (OVER PUSH, WSS/IPC; `van_subscribe`; params; ['minimalConsensusInfo', {fromEpoch: number}]
    -> {... "result":"0xcd0c3e8af590364c09d0fa6a1210faf5"}
    notification: {..., "method":"orc_subscription","params": {"subscription":"0xcd0c3e8af590364c09d0fa6a1210faf5","result": {
     "epoch": 0,
     "validatorList": ["BLS_KEY1", "BLS_KEY2", ...], // turn 0-31
     "epochTimeStart": 1615845764,
     "slotTimeDuration": 6
}})) // fires for each information set
```

**Comment by atif-konasl** [comment]
FYI, vanguard will publish this object -
```go
type MinimalEpochConsensusInfo struct {
	// Epoch number
	Epoch            uint64        `json:"epoch"`
	// Validators public key list for specific epoch
	ValidatorList    [32]string    `json:"validatorList"`
	EpochStartTime   uint64        `json:"epochTimeStart"`
	SlotTimeDuration time.Duration `json:"slotTimeDuration"`
}
```

**Comment by mxmar** [comment]
It's done.
